QT.gui_private.VERSION = 6.9.2
QT.gui_private.name = QtGui
QT.gui_private.module =
QT.gui_private.libs = $$QT_MODULE_LIB_BASE
QT.gui_private.includes = $$QT_MODULE_INCLUDE_BASE/QtGui/6.9.2 $$QT_MODULE_INCLUDE_BASE/QtGui/6.9.2/QtGui
QT.gui_private.frameworks = 
QT.gui_private.depends = core_private gui
QT.gui_private.uses = 
QT.gui_private.module_config = v2 internal_module
QT.gui_private.enabled_features = emojisegmenter freetype system-freetype harfbuzz vkgen gif ico jpeg system-jpeg png system-png imageio-text-loading tuiotouch multiprocess raster-64bit raster-fp qtgui-threadpool graphicsframecapture run-opengl-tests
QT.gui_private.disabled_features = accessibility-atspi-bridge directfb directwrite directwrite3 directwritecolrv1 direct2d direct2d1_1 evdev vxworksevdev fontconfig system-harfbuzz qqnx_imf integrityfb kms drm_atomic libinput integrityhid libinput-axis-api libinput-hires-wheel-support linuxfb vsp2 vnc mtdev vkkhrdisplay egl_x11 eglfs eglfs_brcm eglfs_egldevice eglfs_gbm eglfs_vsp2 eglfs_mali eglfs_viv eglfs_rcar eglfs_viv_wl eglfs_openwfd eglfs_x11 tslib xcb-glx xcb-egl-plugin xcb-native-painting xrender xcb-xlib xcb-sm system-xcb-xinput xkbcommon xkbcommon-x11 xlib
QMAKE_INCDIR_FREETYPE = /Users/akashagr/musclequant/.conda-envs/musclequant-gui/include/freetype2
QMAKE_LIBS_FREETYPE = -lfreetype
QMAKE_LIBS_FONTCONFIG = -lfontconfig
QMAKE_INCDIR_HARFBUZZ = /Users/akashagr/musclequant/.conda-envs/musclequant-gui/include/harfbuzz
QMAKE_LIBS_HARFBUZZ = -lharfbuzz
QMAKE_LIBS_LIBJPEG = -ljpeg
QMAKE_LIBS_LIBPNG = -lpng -lz
QMAKE_LIBS_OPENGL = -framework OpenGL
